# Generated by Django 5.1.2 on 2024-10-22 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Unique flight number', max_length=20, unique=True)),
                ('source', models.CharField(help_text='The starting point of the flight', max_length=100)),
                ('destination', models.CharField(help_text='The destination of the flight', max_length=100)),
                ('takeoff_time', models.DateTimeField(help_text='Time when the flight is scheduled to take off')),
                ('landing_time', models.DateTimeField(help_text='Time when the flight is scheduled to land')),
                ('pilot_name', models.CharField(help_text='Name of the pilot in charge of the flight', max_length=100)),
                ('crew_count', models.PositiveIntegerField(default=5, help_text='Number of crew members on board')),
                ('ticket_price', models.DecimalField(decimal_places=2, help_text='Price of a ticket in USD', max_digits=8)),
                ('available_seats', models.PositiveIntegerField(help_text='Total number of available seats for this flight')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('in_flight', 'In Flight'), ('landed', 'Landed'), ('canceled', 'Canceled')], default='scheduled', help_text='Current status of the flight', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Model of the plane', max_length=100)),
                ('manufacture_date', models.DateField(help_text='Date when the plane was manufactured')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('decommissioned', 'Decommissioned')], default='active', help_text='Current status of the plane', max_length=20)),
                ('number_of_seats', models.PositiveIntegerField(help_text='Total number of seats in the plane')),
                ('serial_number', models.CharField(help_text='Unique serial number of the plane', max_length=50, unique=True)),
                ('last_maintenance_date', models.DateField(blank=True, help_text='Date of last maintenance', null=True)),
                ('flight_hours', models.PositiveIntegerField(default=0, help_text='Total flight hours the plane has completed')),
                ('fuel_capacity', models.DecimalField(decimal_places=2, help_text='Fuel capacity in liters', max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the plane in kilograms', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(help_text="Passenger's full name", max_length=100)),
                ('passenger_passport', models.CharField(help_text="Passenger's passport number", max_length=50)),
                ('passenger_email', models.EmailField(help_text="Passenger's email address", max_length=254)),
                ('passenger_phone', models.CharField(help_text="Passenger's contact phone number", max_length=15)),
                ('seat_number', models.CharField(help_text='Assigned seat number', max_length=5)),
                ('booking_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', help_text='Current status of the booking', max_length=10)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the booking was made')),
                ('checked_in', models.BooleanField(default=False, help_text='Has the passenger checked in?')),
                ('luggage_count', models.PositiveIntegerField(default=0, help_text='Number of luggage items')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price of the booking in USD', max_digits=8)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mainapp.flight')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='mainapp.plane'),
        ),
    ]
