# Generated by Django 5.1.2 on 2024-10-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_seats',
            field=models.PositiveIntegerField(help_text='Assigned seat number', null=True),
        ),
    ]
